---

# Usage: configure.yml
listen_ip: "0.0.0.0"
dhcp_netmask: "24"
domain_private: "local"
domain_public: "public"

# Usage: grendel.yml
grendel_image_name: grendel
grendel_image_tag: v0.0.7.2
grendel_volume: /data/grendel

# Usage: mapping_file.yml
mapping_file_temp: "../../inputs/{{ REGION }}/_temp"
etc_hosts_local: ""

# Usage: kickstart.yml
invalid_root_password: "Incorrect root_password provided"
kickstart_partition: ""
kickstart_repository: ""
kickstart_runonce: ""
kickstart_packages: |
  vim
  kernel-headers
  kernel-devel
  net-tools
  nfs-utils
kickstart_ntp: ""
kickstart_network: ""
kickstart_ssh: ""
kickstart_common: ""
kickstart_diy: ""
## These are default values if we don't set in inputs/REGION
ssh_authorized_keys: []

# Usage: repository.yml
invalid_iso_file_path: "Incorrect path_for_os_iso_file provided"
centos_repo_path: centos
ubuntu_repo_path: ubuntu

# These are default values if we don't set in inputs/REGION
path_for_centos_iso_file: /opt/re/os/CentOS-7-x86_64-Everything-2009.iso
path_for_ubuntu_iso_file: /opt/re/os/ubuntu-23.04-live-server-amd64.iso
