---

- name: repository | Assert valid centos_iso_file_path
  ansible.builtin.stat:
    path: "{{ path_for_centos_iso_file }}"
    get_checksum: no
  register: result_path_centos_iso_file
  tags:
    - grendel_run
    - repository

- name: repository | Assert valid ubuntu_iso_file_path
  ansible.builtin.stat:
    path: "{{ path_for_ubuntu_iso_file }}"
    get_checksum: no
  register: result_path_ubuntu_iso_file
  tags:
    - grendel_run
    - repository

- name : Incorrect centos_iso_file_path
  ansible.builtin.fail:
    msg: "{{ invalid_iso_file_path }}"
  when: ( result_path_centos_iso_file.stat.exists == false ) or ( ".iso" not in path_for_centos_iso_file )
  tags:
    - grendel_run
    - repository

- name : Incorrect ubuntu_iso_file_path
  ansible.builtin.fail:
    msg: "{{ invalid_iso_file_path }}"
  when: ( result_path_ubuntu_iso_file.stat.exists == false ) or ( ".iso" not in path_for_ubuntu_iso_file )
  tags:
    - grendel_run
    - repository

- name: repository | Fail when iso path valid but image not right
  ansible.builtin.fail:
    msg: "{{ invalid_iso_file_path }}"
  when: ( result_path_centos_iso_file.stat.exists == true ) and ( ".iso" not in path_for_centos_iso_file )
  tags:
    - grendel_run
    - repository

- name: repository | Fail when iso path valid but image not right
  ansible.builtin.fail:
    msg: "{{ invalid_iso_file_path }}"
  when: ( result_path_ubuntu_iso_file.stat.exists == true ) and ( ".iso" not in path_for_ubuntu_iso_file )
  tags:
    - grendel_run
    - repository

- name: repository | Create repository directory
  ansible.builtin.file:
    path: "{{ grendel_volume }}/opt/os/{{ item }}"
    state: directory
  loop:
    - "{{ centos_repo_path }}"
    - "{{ ubuntu_repo_path }}"
  tags:
    - grendel_run
    - repository

- name: repository | Create iso repository directory
  ansible.builtin.file:
    path: "{{ grendel_volume }}/opt/iso"
    state: directory
  tags:
    - grendel_run
    - repository

- name: repository | Umount the centos iso file
  ansible.posix.mount:
    path: "{{ grendel_volume }}/opt/os/{{ centos_repo_path }}"
    state: unmounted
  tags:
    - grendel_run
    - repository

- name: repository | Umount the ubuntu iso file
  ansible.posix.mount:
    path: "{{ grendel_volume }}/opt/os/{{ ubuntu_repo_path }}"
    state: unmounted
  tags:
    - grendel_run
    - repository

- name: repository | Mount the centos iso file
  ansible.posix.mount:
    path: "{{ grendel_volume }}/opt/os/{{ centos_repo_path }}"
    src: "{{ path_for_centos_iso_file }}"
    opts: loop
    boot: false
    fstype: iso9660
    state: mounted
  tags:
    - grendel_run
    - repository

- name: repository | Mount the ubuntu iso file
  ansible.posix.mount:
    path: "{{ grendel_volume }}/opt/os/{{ ubuntu_repo_path }}"
    src: "{{ path_for_ubuntu_iso_file }}"
    opts: loop
    boot: false
    fstype: iso9660
    state: mounted
  tags:
    - grendel_run
    - repository

- name: repository | Link the ubuntu iso file
  ansible.builtin.file:
    src: "{{ path_for_ubuntu_iso_file }}"
    dest: "{{ grendel_volume }}/opt/iso/ubuntu.iso"
    state: link
  tags:
    - grendel_run
    - repository
