---

- name: history | Generate history config files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0644'
    backup: yes
  with_items:
    - { src: 'etc/profile.d/history.sh.j2', dest: '/etc/profile.d/history.sh' }
    - { src: 'etc/rsyslog.d/history.conf.j2', dest: '/etc/rsyslog.d/history.conf' }
    - { src: 'etc/logrotate.d/history.j2', dest: '/etc/logrotate.d/history' }
  notify:
    - Restart rsyslog
  tags:
    - audit
    - history
    - rsyslog
