---

kickstart_hosts: |

  # download from grendel server and write to /etc/hosts
  %post --log=/var/log/re/ks_post-hosts.log
  {% raw %}
  cd /dev/shm; curl -O {{ .baseuri }}/repo/sync/hosts
  [ $? -eq 0 ] && /usr/bin/cp -fv /dev/shm/hosts /etc/hosts
  {% endraw %}
  %end