---

# The directory where (and how) to cache.
squid_cache_dir: ufs /var/spool/squid 100 16 256

# Location of squid's log file
squid_access_log: /var/log/squid/access.log

squid_image: ubuntu/squid
squid_version: 5.2-22.04_beta
squid_container: squid
squid_port: 3128
