---

- name: sge_execution | Install sge execution packages only
  ansible.builtin.yum:
    name: "{{ sge_execution_pkgs }}"
    state: present
    disable_gpg_check: true
  vars:
    sge_execution_pkgs:
      - "{{ extra_packages_url }}/rpm/{{ sge_rpm }}"
      - m4
  tags: yum, sge

- name: sge_execution | Copy installation config file to destination
  ansible.builtin.template:
    src: installation.conf.j2
    dest: "{{ sge_root }}/installation.conf"
  tags: sge_execution

- name: sge_execution | Create sge cell directory
  ansible.builtin.file:
    path: "{{ sge_root }}/{{ cell_name }}/common"
    state: directory
    recurse: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  tags: sge_execution

- name: sge_execution | Generate sge common configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ sge_root }}/{{ cell_name }}/common/{{ item }}"
  with_items:
    - act_qmaster
    - bootstrap
    - cluster_name
    - settings.csh
    - settings.sh
    - sgeexecd
  tags: sge_execution

- name: sge_execution | Change sgeexecd file permission
  ansible.builtin.file:
    dest: "{{ sge_root }}/{{ cell_name }}/common/sgeexecd"
    mode: 0755

- name: sge_execution | Configure sge execution only
  ansible.builtin.command: ./inst_sge -noremote -x -auto installation.conf
  args:
    chdir: "{{ sge_root }}"
    creates: /etc/init.d/sgeexecd*
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
  tags: sge_execution

- name: sge_execution | Configure sge execution only
  ansible.builtin.command: ./inst_sge -noremote -x -auto installation.conf
  args:
    chdir: "{{ sge_root }}"
    creates: /etc/systemd/system/sgeexecd.service
  when: ansible_distribution == "Rocky" and ansible_distribution_major_version == "8"
  tags: sge_execution

- name: sge_execution | Wait for 60s before starting sge service
  ansible.builtin.wait_for:
    timeout: 60

- name: sge_execution | Enable sge execution service
  ansible.builtin.service:
    name: "sgeexecd.{{ sge_cluster_name }}"
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
  tags: sge_execution

- name: sge_execution | Enable sge execution service
  ansible.builtin.service:
    name: "sgeexecd"
    enabled: yes
    state: started
  when: ansible_distribution == "Rocky" and ansible_distribution_major_version == "8"
  tags: sge_execution
