- name: Start nrpe
  ansible.builtin.service:
    name: nrpe
    state: restarted
    enabled: yes
  ignore_errors: true

- name: Restart dbus
  ansible.builtin.service:
    name: dbus
    state: restarted
    enabled: yes
  ignore_errors: true

- name: Restart systemd-logind
  ansible.builtin.service:
    name: systemd-logind
    state: restarted
    enabled: yes
  ignore_errors: true
