---

sge_root: "/opt/gridengine"
sge_qmaster_port: 6444
sge_execd_port: 6445
sge_cluster_name: "re-{{ REGION }}"
cell_name: default
admin_user: sge
gid_range: "20000-20200"
sge_master_hostname: localhost
sge_execd_ulimit: 204800