---

- name: assert | Test if docker_required_packages is set correctly
  ansible.builtin.assert:
    that:
      - docker_required_packages is defined
      - docker_required_packages is iterable
    quiet: yes
  tags:
    - assert

- name: assert | Test if docker_ce_mirror is set correctly
  ansible.builtin.assert:
    that:
      - docker_ce_mirror is defined
      - docker_ce_mirror is string
    quiet: yes
  tags:
    - assert
