---

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Set proxy environment
  ansible.builtin.import_tasks: proxy.yml

- name: Prepare requirement
  ansible.builtin.import_tasks: requirement.yml

- name: Install docker
  ansible.builtin.import_tasks: install.yml