---

- name: requirement | Install required packages
  ansible.builtin.package:
    name: "{{ docker_required_packages }}"
    state: present
  environment: "{{ proxy_env }}"
  tags:
    - requirement

- name: requirement | Install docker using pip
  ansible.builtin.pip:
    name: docker
    executable: pip3
    state: present
  environment: "{{ proxy_env }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - requirement
