---

- name: assert | Test if nexus_server is set correctly
  ansible.builtin.assert:
    that:
      - nexus_server is defined
      - nexus_server is string
      - nexus_server is not none
    quiet: yes
  tags:
    - assert

- name: assert | Test if nexus_port is set correctly
  ansible.builtin.assert:
    that:
      - nexus_port is defined
      - nexus_port is number
      - nexus_port > 0
      - nexus_port < 65536
    quiet: yes
  tags:
    - assert
