
# ganglia
[ganglia:children]
gmetad
gmond

[gmetad:children]
sge_qmaster

[gmond:children]
sge_qmaster
sge_submit
sge_execution
gpu

# sge
[sge:children]
sge_qmaster
sge_submit
sge_execution
gpu

[sge_qmaster]

[sge_submit]

[sge_execution]

[gpu]
